//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedReport
    {
        public int DetailedReport_ID { get; set; }
        public Nullable<int> Quiz_ID { get; set; }
        public Nullable<int> Question_ID { get; set; }
        public Nullable<int> AttemptedAnswer { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual User User { get; set; }
    }
}
