//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quiz()
        {
            this.DetailedReports = new HashSet<DetailedReport>();
            this.QuizSchedules = new HashSet<QuizSchedule>();
            this.Reports = new HashSet<Report>();
        }
    
        public int Quiz_ID { get; set; }
        public string Question_IDs { get; set; }
        public Nullable<int> Difficulty { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public Nullable<int> TotalQuestions { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
        public Nullable<int> ArchiveStatus { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string QuizType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailedReport> DetailedReports { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizSchedule> QuizSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
