//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Report_ID { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<int> Quiz_ID { get; set; }
        public Nullable<int> CorrectAnswers { get; set; }
        public Nullable<int> WrongAnswers { get; set; }
        public Nullable<decimal> TimeTaken { get; set; }
        public Nullable<int> UnattemptedAnswers { get; set; }
        public Nullable<decimal> Accuracy { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
        public string QuizType { get; set; }
        public Nullable<int> Subject_ID { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
    }
}
